import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import { SiteLayout } from '@components/common';
// import styles from '../styles/Home.module.css'

//For Pages, use 'function' syntax to allow for .getLayout
// I prefer this syntax in future:
// const Home: FC<NextPage> = () => {
export default function Home<NextPage>() {
  return (
    <>
      <div>I am Home Component</div>
      <div className="REMOVE_ME">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="REMOVE_ME">
          <h1 className="REMOVE_ME">
            Welcome to <a href="https://nextjs.org">Craig's Website!</a>
          </h1>

          <p className="REMOVE_ME">
            Get started by editing{' '}
            <code className="REMOVE_ME">pages/index.tsx</code>
          </p>

          <div className="REMOVE_ME">
            <a href="https://nextjs.org/docs" className="REMOVE_ME">
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className="REMOVE_ME">
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className="REMOVE_ME"
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className="REMOVE_ME"
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </main>

        <footer className="REMOVE_ME">
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className="REMOVE_ME">
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
}

Home.getLayout = SiteLayout;
