tf_state_bucket        = "craig-watt-tfstate"
tf_state_lock_table    = "craig-watt-lock-table"
github_oidc_provider_url = "https://token.actions.githubusercontent.com"
github_repo           = "CraigWatt/craig-watt-website"
image_tag             = "v0.6.10"
ecs_execution_role_arn = "arn:aws:iam::275578070934:role/ecsTaskExecutionRole"
ecs_task_role_arn     = "arn:aws:iam::275578070934:role/ecsTaskRole"
