import './global.css';
import { Providers } from './providers';
import { Navbar } from './components/Navbar';
export const metadata = {
  title: 'Welcome to nextjs-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white text-zinc-900 dark:bg-zinc-900 dark:text-white">
        <Navbar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
