# .github/workflows/keep-trading212-cache-warm.yml

# This job only runs on a schedule—no need to trigger on push/PR.
on:
  schedule:
    # Every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  warm:
    runs-on: ubuntu-latest

    steps:
      - name: Warm T212 API cache
        run: |
          echo "Warming https://craigwatt.co.uk/api/trading212"
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://craigwatt.co.uk/api/trading212)
          echo "HTTP status: $STATUS"
          if [ "$STATUS" -ne 200 ]; then
            echo "❌ Cache warm failed with status $STATUS"
            exit 1
          fi
